language: go

go:
  - 1.9.x

env:
  - DEP_VERSION="0.3.2"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega

script: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2
